# Site settings
title: Christopher Zerafa
description: Christopher Zerafa Github Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Christopher Zerafa
user_description: I am a data scientist with relevant work experience and proven academic track record. I used to identify hydrocarbons within the subsurface using data, but I now gain business insights from different data sources, employ original modelling techniques and imporove on business ROI.
user_title: Data Scientist
email: zerafachris@gmail.com
# twitter_username: lorem_ipsum
github_username:  zerafachris
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
